# Generated by Django 3.2.14 on 2023-03-31 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('university_units', '0004_office_contact_number'),
        ('news', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 18, 48, 53, 215569, tzinfo=utc), verbose_name='Puplish Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university_units.office', verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anouncement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_units.office', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Category'),
        ),
    ]
