# Generated by Django 3.2.14 on 2023-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideentry',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='guideentry',
            name='created',
            field=models.DateTimeField(auto_created=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='guideentry',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='guideentry',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Updated At'),
        ),
    ]
