# Generated by Django 3.2.14 on 2023-03-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_units', '0004_office_contact_number'),
        ('student_guide', '0002_auto_20230313_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideentry',
            name='image',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Guide Entry Image'),
        ),
        migrations.AddField(
            model_name='guideentry',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university_units.office', verbose_name='Unit'),
            preserve_default=False,
        ),
    ]
