# Generated by Django 3.2.14 on 2023-03-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('year_calendar', '0002_auto_20230312_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exception',
            new_name='Exceptions',
        ),
        migrations.RemoveField(
            model_name='eventparent',
            name='exceptions',
        ),
        migrations.AddField(
            model_name='eventparent',
            name='exception',
            field=models.ManyToManyField(to='year_calendar.Exceptions', verbose_name='Exceptions'),
        ),
    ]
