# Generated by Django 3.2.14 on 2023-03-12 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('year_calendar', '0003_auto_20230312_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptions',
            name='parent',
        ),
        migrations.AddField(
            model_name='event',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 20, 46, 31, 264004, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 20, 46, 57, 229931, tzinfo=utc), verbose_name='Event Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.IntegerField(default=1, verbose_name='Event Importance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='year_tag',
            field=models.CharField(default=datetime.datetime(2023, 3, 12, 20, 47, 33, 440067, tzinfo=utc), max_length=50, verbose_name='Year Tag'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventParent',
        ),
    ]
