# Generated by Django 3.2.14 on 2023-03-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year_calendar', '0004_auto_20230312_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Year Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='year_tag',
            field=models.CharField(choices=[], max_length=50, verbose_name='Year Tag'),
        ),
    ]
