# Generated by Django 3.2.14 on 2023-03-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('year_calendar', '0007_alter_event_year_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='year_calendar.academicyear', verbose_name='Year'),
        ),
    ]
