# Generated by Django 3.2.14 on 2023-03-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('year_calendar', '0008_alter_event_year_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='tag',
            new_name='name',
        ),
    ]
