# Generated by Django 3.2.14 on 2023-03-31 18:49

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('college', '0002_alter_college_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Year Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(default='Describtion', verbose_name='College Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='contact',
            field=models.CharField(max_length=16, verbose_name='College Contact Number'),
        ),
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.TextField(verbose_name='College Location'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='College Name'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.batch', verbose_name='Batch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='College')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='College'),
        ),
    ]
