# Generated by Django 3.2.14 on 2023-03-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_units', '0002_office_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
