# Generated by Django 3.2.14 on 2023-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_units', '0003_alter_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='contact_number',
            field=models.CharField(default='249113075979', max_length=15),
            preserve_default=False,
        ),
    ]
